batch_size:
  desc: Batch size
  value: 32
triplet_loss_margin:
  desc: Triplet loss margin
  value: 2.0
epochs:
  desc: Max epochs to train for
  value: 20
lr:
  desc: Learning rate
  value: 0.01
patience_scheduler:
  value: 2
hidden_sizes:
  desc: Hidden sizes of projection head 
  value: [512,512,512]
emb_dim:
  desc: Projection dimension
  value: 32
  

