train_dir:
  desc: Train dir path
  value: 'data/stamps/stamps'
batch_size:
  desc: Batch size
  value: 64
triplet_loss_margin:
  desc: Triplet loss margin
  value: 2.0
epochs:
  desc: Max epochs to train for
  value: 1000
lr:
  desc: Learning rate
  value: 0.001
patience_scheduler:
  value: 4
hidden_sizes:
  desc: Hidden sizes of projection head 
  value: [1024,512,512,512]
emb_dim:
  desc: Projection dimension
  value: 512
checkpoint_path:
  desc: Checkpoint to start training from
  value: False
  

